<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ApplicationIcon>../Assets/icon.ico</ApplicationIcon>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IlcTreatWarningsAsErrors>false</IlcTreatWarningsAsErrors>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.0.0</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="4.1.3" />
    <PackageReference Include="SkiaSharp" Version="4.153.1" />
    <PackageReference Include="Svg.Skia" Version="5.2.3" />
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
    <PackageReference Include="Velopack" Version="1.2.161" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VectorToCursor.Tests" />
  </ItemGroup>

  <Target Name="StripPdbsFromPublish" AfterTargets="ComputeResolvedFilesToPublishList">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(Extension)' == '.pdb'" />
    </ItemGroup>
  </Target>

</Project>
